notifications:
  email: false
sudo: enabled
os: linux
language: python
python: 3.8-dev
cache: pip
env:
  global:
    - GH_REPO=Drakkar-Software/OctoBot-Services
    - DEPLOY_BRANCH=master
    - PACKAGE_FOLDER=octobot_services
    - secure: apv6/DPB7AKIjsevHn6F6GQty4AU3AFX4GYQqRfAeLingK4zHQ9SWAvbI7pwvhF2MJ6l0fDaOtV6nhuptt1SCwAn5+O/gltj6Mc/ohsZzbj8+39UTBazOnocdlQFpjIxwUHOC3AT89MjOH2JBGanZiM240ewxKsGK5L4SJ6YHfRNXzz+4ul3SvyaBL+ThqI0k3X42Bfu1SxYdDfzYzm9VOk69y/8Ny1SvSxaBpPW/V0No64QDcYe7FXsrau1a2UrPcHRNyAmQ7l1lbXscQITgzMLKOsYGYGTTUoyAl0RVvL28OQl0ZDHM0TVRcVBtu43VSyzul/8mOj4ZZE9bDbisVxXXziG2thEFmVzZV1xthPbhR33cxUGRF6JUAiVWJ4+big7IvCaLTcuFAyqrxvHZ1frGi1bW0csHHSyj5oLhZrsalg9TPhGwCk/s62gKY2CF/WzmsPzsQhVILJGT1KRfPqGOOc11QwSIWKlWNGEndJWGEoLVZO9Jz/c/nbS6urVA/6UNirOa/EFfZXEnYexz6iw8JHIsrRHxDF6Sy5HW5iLsvyNqz3IDJobWzcYqgGVGcpw1ayCRl41lmosMBg0L/uuHLh4kEK5yJadFMYoxL0A8rSOIBrBgFCcg+MukZF2+44+AS9HAIOP4AEMumM9ix8o+NCY8ZKl3QeZcmwwnVo=
    - secure: JtUcuCrcOu45t7VgSkjjqXgKpSaQRhfUE/2usnCDCYa1zwIbePqrncfTMYX2NFzYngFAegqoQP7b3TADj+0m07TENCc1SVYnzO/jPseZEGE/rskRN9aRa/VpHwhXmvtAtOIlzDDeJ4Q2+/BcJuIdDdBPzfZFGHHIFfagQpzQyffhq2msy82NI6D0SRa7evx0YyrERZRwl3pLNQ50xY+NFADFnPNI9zzpk92x4K7E+ByM6KX3XcQiuURW6iBdr+fRk5hyrS8emWCF9Pc1goxMG3mw/6d8bfKWRQBXnNtoQdvNQQfLmHM3t65LkzFaubiummhUhFQM0byqhtEbPcgR7+ILTZier/4Ge+gYVjCfveOg44wE0DbKcmlYm2WVeXRdcunnrHhM+WX+SIQFvYc4LGgYcVUc7LRXIwTTw3i27a2qC7qW/wXoEI1+lCuOlas04HB8O8IshpLrEXVEPNr4ksoRgoCJjc8+ycpUvD8hCJghudml6MiZDIlkiHaNsfYNkP/dd0JI75V9AwvBiZdbkHPt+cKtkRILE1bvvq/DGhc24tRAjaMCWAMYcRWh1iKj+P6vbLSaWqEZp0/8U27KX4L+d7/vmy+cfIfxTJOElfqqJqa4/E/MWZUOS04QYAmUJeqwpvczW+4+FjWYRIdspKjYzPUK205CFLw9QukYkb0=

install:
  - python3 -m pip install --prefer-binary -r dev_requirements.txt -r requirements.txt

matrix:
  include:
    - name: "Linux - Python 3.8-dev - Python sources"
      stage: test
      os: linux
      python: 3.8-dev
      language: python
      script:
        - pytest --cov=. --cov-config=.coveragerc --durations=0 -rw tests
      after_success:
        - if [ $TRAVIS_PULL_REQUEST == "false" ]; then coveralls; fi

    - name: "Linux - Python 3.8-dev - Installed"
      stage: test
      os: linux
      python: 3.8-dev
      language: python
      script:
        - python3 setup.py build_ext --inplace
        - python3 setup.py install
        - rm -rf $PACKAGE_FOLDER
        - pytest tests

    - name: "Linux - Python 3 - Deploy"
      stage: deploy
      script:
        - ls
      deploy:
        - provider: pypi
          user: "__token__"
          password:
            secure: RFAdYo5+NhovKvU3PPlY+IDKNFni3b5tJWNegLLUgotgD6XfAACEXCi0MhZfdLGnFyuB/5L6i4W2VMiAqE9ToiEPxJ9gqJHC539Wp0hPXs1nXMNIB4U1imbT0h2agr+cejKWhGN7EkayYlZUAJAMQKXo3+ERokleE09Z/pSoW5jx/qU3aKjsBoTwKCN3Le+onzpw+5csvfjL5MQisM4AfvTV913hdJ43uKe0lByJI1uwwZIw80vaBvtw6BTt8v+DyZrWvmLExhjnmHGJycuLftbeknjhAUCpCU3mFYkVYDB9HO4DC4OOAueZfEr4fk19SaiUShrdJ3rU8Iyr+5KyS1xGBBZUSnNaRFbioogQM0pPjGv9KG1QmN08bMwCcNo8w5aNhu+w6S32+bak6YMUExsmqZwq2Cr6axo/XfHu/Cf6YTgTw9HdInoIuX6tdf+MBThV6vcjdDuP7otX9YgJ2XnTa2WqIp0N9uuAoeJTvDa8YpCPimfIfSitfsshHDWS+l/ETbFlajeChMQo9RLzZ/7wH/kAVn6oriyFnWDUZKPvQ3KSFsfyBbTKHc7f+lTZw06ZvyeM2eH2HgIhbQlwY3ShUZqoq5CxoPKDMHEdHuurPl74nTyitgSVK0SgGcBDO1hrH9kXNYQI++VZ5xwlJLQeV6ytD1/4avDqDCXyYq8=
          skip_cleanup: true
          skip_existing: true
          distributions: "sdist"
          on:
            repo: $GH_REPO
            branch: $DEPLOY_BRANCH
            tags: true
            condition: $TRAVIS_OS_NAME = 'linux'
        - provider: script
          script: docker run -it -e PYPI_USERNAME=$PYPI_USERNAME -e PYPI_PASSWORD=$PYPI_PASSWORD -v $(pwd):/project drakkarsoftware/octobot-pypi-deploy:i686 "i686" "cp37-cp37m" "cp37"
          skip_cleanup: true
          skip_existing: true
          on:
            repo: "$GH_REPO"
            branch: "$DEPLOY_BRANCH"
            tags: true
            condition: "$TRAVIS_OS_NAME = 'linux'"
        - provider: script
          script: docker run -it -e PYPI_USERNAME=$PYPI_USERNAME -e PYPI_PASSWORD=$PYPI_PASSWORD -v $(pwd):/project drakkarsoftware/octobot-pypi-deploy:x86_64 "x86_64" "cp37-cp37m" "cp37"
          skip_cleanup: true
          on:
            repo: "$GH_REPO"
            branch: "$DEPLOY_BRANCH"
            tags: true
            condition: "$TRAVIS_OS_NAME = 'linux'"

    - name: "OSX - Python 3.7 - Deploy"
      stage: deploy
      os: osx
      osx_image: xcode11    # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      # python: 3.7         # 'python:' is ignored on Travis CI macOS
      before_install: python3 --version ; pip3 --version ; sw_vers
      install:
        - python3 -m pip install --prefer-binary --user -r requirements.txt
        - python3 -m pip install --prefer-binary -r dev_requirements.txt
      before_cache:
        - rm -f "$HOME/Library/Caches/pip/log/debug.log"
      cache:
        directories:
          - "$HOME/Library/Caches/pip"
      script:
        - python3 setup.py build_ext --inplace
        - pytest tests
      deploy:
        - provider: script
          script: python3 setup.py bdist_wheel && python3 -m twine upload dist/* -u $PYPI_USERNAME -p $PYPI_PASSWORD --skip-existing
          skip_cleanup: true
          on:
            repo: "$GH_REPO"
            branch: "$DEPLOY_BRANCH"
            tags: true
            condition: "$TRAVIS_OS_NAME = 'osx'"
